version: '3.8'

services:
  mynginx:
    user: "nginxuser:nginxuser_g"
    image: my-nginx:1.1
    build: .
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/data/html
    restart: unless-stopped